version: '3'
services:
  mysql:
    container_name: rough-erd-mysql
    image: mysql:5.7
    ports:
      - "23306:3306"
    volumes:
      - ./db/mysql/init:/docker-entrypoint-initdb.d # create_table
    environment:
      MYSQL_ROOT_PASSWORD: rough-erd
      MYSQL_USER: user
      MYSQL_PASSWORD: pw
      MYSQL_DATABASE: test